### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by tivac** [typicode/tlapse#2]
Trying to run `tlapse` for the first time and I'm getting an error.

```
$ tlapse -- localhost:3000

Screenshots directory: ./tlapse
Interval: 1m
C:\Users\Patrick\Documents\Code\gw2api-explorer\node_modules\tlapse\index.js:67
    if (latestFile.indexOf('.png.') !== -1) {
                  ^

TypeError: Cannot read property 'indexOf' of undefined
    at run (C:\Users\Patrick\Documents\Code\gw2api-explorer\node_modules\tlapse\index.js:67:19)
    at Object.<anonymous> (C:\Users\Patrick\Documents\Code\gw2api-explorer\node_modules\tlapse\index.js:85:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

The `tlapse` directory is created successfully, but it seems like it's barfing when trying to find a previous screenshot when one doesn't exist. I guess I'll try and make one manually?

**Comment by tivac** [comment]
I worked around this by creating a bogus `tlapse/temp.png` file and tlapse started successfully. Then I ran face-first into #3 because I'm on Windows.

**Comment by typicode** [comment]
Hi @tivac,

Thanks for the report, I didn't encounter this issue when testing.
I'll publish a fix today.

**Comment by typicode** [comment]
Should be good in `v0.1.4`
