### ISSUE TITLE
const childProcess = require('child_process');

### ISSUE THREAD

**Issue by bobmeliev** [typicode/tlapse#9]
Hi there, 

I can't start tlapse, here is console output:

```
tlapse --every 30s -- localhost:8080

/usr/local/lib/node_modules/tlapse/node_modules/execa/index.js:2
const childProcess = require('child_process');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tlapse/index.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Ubuntu 14.04.5 LTS

nodejs --version
v0.10.25

npm --version
1.3.10

**Comment by HugoDF** [comment]
@bobmeliev I believe the `const` keyword is not supported in strict mode on Node V0.10 ([compat table](http://node.green/#ES2015-bindings-const-basic-support--strict-mode-)), the easiest solution is probably to upgrade your Node version, see also [this answer on StackOverflow](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode).

**Comment by typicode** [comment]
+1  also Node 0.10 isn't supported anymore (thanks @HugoDF)

Personally, I like https://github.com/creationix/nvm on Ubuntu, but you're free to use whatever you prefer :)
